#!/usr/bin/env python3
"""CLI for onspy MCP server.

Generated by: fastmcp generate-cli src/onspy/server.py
Then patched: CLIENT_SPEC uses package-relative path, app name = "onspy".
"""

import json
import sys
from pathlib import Path
from typing import Annotated

import cyclopts
import mcp.types
from rich.console import Console

from fastmcp import Client
from fastmcp.client.transports import StdioTransport

# Resolve server.py relative to this file (works when installed as a package).
_SERVER_PY = str(Path(__file__).with_name("server.py"))
CLIENT_SPEC = StdioTransport(
    command="fastmcp",
    args=["run", _SERVER_PY, "--no-banner"],
)

app = cyclopts.App(name="onspy", help="ONS (Office for National Statistics) Data CLI")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp.types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp.types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp.types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp.types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(
    uri: Annotated[str, cyclopts.Parameter(help="Resource URI")],
) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(
                f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value"
            )
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(
                    f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]"
                )
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------


@call_tool_app.command(name="list_datasets")
async def list_datasets(
    *,
    limit: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "integer"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
) -> None:
    """List all available ONS datasets with metadata.

    Returns datasets with id, title, description, keywords, release
    frequency, and publication state."""
    # Parse JSON parameters
    limit_parsed = json.loads(limit) if isinstance(limit, str) else limit

    await _call_tool("list_datasets", {"limit": limit_parsed})


@call_tool_app.command(name="get_dataset_ids")
async def get_dataset_ids() -> None:
    """Get a simple list of all dataset IDs.

    Useful for scripting and discovering what datasets exist."""
    await _call_tool("get_dataset_ids", {})


@call_tool_app.command(name="get_dataset_info")
async def get_dataset_info(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """Get detailed information about a specific dataset.

    Returns title, description, keywords, release frequency, state,
    next release date, latest version, and available editions.

    Args:
        id: Dataset ID (e.g., \'cpih01\', \'weekly-deaths-region\')"""
    await _call_tool("get_dataset_info", {"id": id})


@call_tool_app.command(name="get_editions")
async def get_editions(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """List available editions for a dataset.

    Args:
        id: Dataset ID"""
    await _call_tool("get_editions", {"id": id})


@call_tool_app.command(name="find_latest_version")
async def find_latest_version(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """Find the latest version across ALL editions of a dataset.

    Some datasets have multiple editions (e.g., \'time-series\', \'covid-19\').
    This checks all editions and returns the one with the highest version.

    Args:
        id: Dataset ID"""
    await _call_tool("find_latest_version", {"id": id})


@call_tool_app.command(name="download_dataset")
async def download_dataset(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
    edition: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
    version: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
    preview_rows: Annotated[int, cyclopts.Parameter(help="")] = 10,
) -> None:
    """Download a dataset from ONS.

    Automatically finds the latest version if edition/version not specified.
    Returns metadata, column names, and a preview of the first N rows.

    Args:
        id: Dataset ID
        edition: Edition name (auto-detects if not provided)
        version: Version number (auto-detects if not provided)
        preview_rows: Number of rows to include in preview"""
    # Parse JSON parameters
    edition_parsed = json.loads(edition) if isinstance(edition, str) else edition
    version_parsed = json.loads(version) if isinstance(version, str) else version

    await _call_tool(
        "download_dataset",
        {
            "id": id,
            "edition": edition_parsed,
            "version": version_parsed,
            "preview_rows": preview_rows,
        },
    )


@call_tool_app.command(name="download_all_parquet")
async def download_all_parquet(
    *,
    output_dir: Annotated[str, cyclopts.Parameter(help="")] = "ons_datasets",
    resume: Annotated[bool, cyclopts.Parameter(help="")] = False,
    delay: Annotated[float, cyclopts.Parameter(help="")] = 2.0,
) -> None:
    """Download every available ONS dataset as parquet.

    Saves one parquet file per dataset in output_dir and writes a
    manifest.json summary for downstream tooling.

    Args:
        output_dir: Target directory for parquet files
        resume: Skip datasets that already exist in output_dir
        delay: Seconds to wait between dataset downloads"""
    await _call_tool(
        "download_all_parquet",
        {"output_dir": output_dir, "resume": resume, "delay": delay},
    )


@call_tool_app.command(name="download_datasets_parquet")
async def download_datasets_parquet(
    *,
    dataset_id: Annotated[
        list[str],
        cyclopts.Parameter(
            name=("--dataset-id",),
            help="Dataset ID to download (repeat --dataset-id for multiple)",
        ),
    ],
    output_dir: Annotated[str, cyclopts.Parameter(help="")] = "ons_datasets",
    resume: Annotated[bool, cyclopts.Parameter(help="")] = False,
    delay: Annotated[float, cyclopts.Parameter(help="")] = 2.0,
) -> None:
    """Download specific ONS datasets as parquet.

    Useful when you only need a subset for local DuckDB analysis.

    Args:
        dataset_id: Dataset ID(s), repeat flag for multiple
        output_dir: Target directory for parquet files
        resume: Skip datasets that already exist in output_dir
        delay: Seconds to wait between dataset downloads"""
    dataset_ids = [item.strip() for item in dataset_id if str(item).strip()]
    if len(dataset_ids) == 0:
        console.print(
            "[bold red]Error:[/bold red] provide at least one --dataset-id value"
        )
        sys.exit(1)

    await _call_tool(
        "download_datasets_parquet",
        {
            "dataset_ids": dataset_ids,
            "output_dir": output_dir,
            "resume": resume,
            "delay": delay,
        },
    )


@call_tool_app.command(name="list_boundaries")
async def list_boundaries() -> None:
    """List curated geography boundary files for choropleth mapping.

    Returns IDs, year, coverage, code column, name column, and source URL."""
    await _call_tool("list_boundaries", {})


@call_tool_app.command(name="download_boundary")
async def download_boundary(
    *,
    boundary_id: Annotated[str, cyclopts.Parameter(help="")],
    output_dir: Annotated[str, cyclopts.Parameter(help="")] = "ons_boundaries",
    overwrite: Annotated[bool, cyclopts.Parameter(help="")] = False,
) -> None:
    """Download a curated boundary GeoJSON file.

    Args:
        boundary_id: Boundary ID from list_boundaries()
        output_dir: Directory to save GeoJSON file
        overwrite: Overwrite if file already exists"""
    await _call_tool(
        "download_boundary",
        {"boundary_id": boundary_id, "output_dir": output_dir, "overwrite": overwrite},
    )


@call_tool_app.command(name="get_dimensions")
async def get_dimensions(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """List available dimensions (filterable columns) for a dataset.

    Dimensions are categorical columns you can filter by when querying
    observations (e.g., \'geography\', \'time\', \'aggregate\').

    Args:
        id: Dataset ID"""
    await _call_tool("get_dimensions", {"id": id})


@call_tool_app.command(name="get_dimension_options")
async def get_dimension_options(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
    dimension: Annotated[str, cyclopts.Parameter(help="")],
    limit: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "integer"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
) -> None:
    """Get available values for a specific dimension.

    Use this to discover valid filter values before calling get_observations.
    For example, get all geography codes or time periods.

    Args:
        id: Dataset ID
        dimension: Dimension name (e.g., \'geography\', \'time\')
        limit: Maximum options to return"""
    # Parse JSON parameters
    limit_parsed = json.loads(limit) if isinstance(limit, str) else limit

    await _call_tool(
        "get_dimension_options",
        {"id": id, "dimension": dimension, "limit": limit_parsed},
    )


@call_tool_app.command(name="get_dimension_options_detailed")
async def get_dimension_options_detailed(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
    dimension: Annotated[str, cyclopts.Parameter(help="")],
    limit: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "integer"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
) -> None:
    """Get dimension options with labels and code-list links.

    Returns option value plus human-readable label and associated
    code/code-list identifiers when available.

    Args:
        id: Dataset ID
        dimension: Dimension name (e.g., 'geography', 'time')
        limit: Maximum options to return"""
    limit_parsed = json.loads(limit) if isinstance(limit, str) else limit

    await _call_tool(
        "get_dimension_options_detailed",
        {"id": id, "dimension": dimension, "limit": limit_parsed},
    )


@call_tool_app.command(name="get_observations")
async def get_observations(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
    filters: Annotated[
        str,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "additionalProperties": {\n                              "type": "string"\n                            },\n                            "type": "object"\n                          }'
        ),
    ],
    edition: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
    version: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
) -> None:
    """Get filtered observations from a dataset.

    All dimensions must be specified.

    Wildcard '*' is supported for table-backed datasets (those with downloadable
    CSV tables). API-only datasets require explicit values for each dimension.

    Call get_dimensions() first to see required filters, then
    get_dimension_options() to see valid values.

    Example filters: {"geography": "K02000001", "aggregate": "cpih1dim1A0", "time": "*"}

    Args:
        id: Dataset ID
        filters: Dictionary mapping dimension names to filter values
        edition: Edition name (auto-detects if not provided)
        version: Version number (auto-detects if not provided)"""
    # Parse JSON parameters
    filters_parsed = json.loads(filters) if isinstance(filters, str) else filters
    edition_parsed = json.loads(edition) if isinstance(edition, str) else edition
    version_parsed = json.loads(version) if isinstance(version, str) else version

    await _call_tool(
        "get_observations",
        {
            "id": id,
            "filters": filters_parsed,
            "edition": edition_parsed,
            "version": version_parsed,
        },
    )


@call_tool_app.command(name="get_metadata")
async def get_metadata(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
    edition: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
    version: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
) -> None:
    """Get metadata for a dataset version.

    Includes contact details, methodology, dimension descriptions, etc.

    Args:
        id: Dataset ID
        edition: Edition name (auto-detects if not provided)
        version: Version number (auto-detects if not provided)"""
    # Parse JSON parameters
    edition_parsed = json.loads(edition) if isinstance(edition, str) else edition
    version_parsed = json.loads(version) if isinstance(version, str) else version

    await _call_tool(
        "get_metadata", {"id": id, "edition": edition_parsed, "version": version_parsed}
    )


@call_tool_app.command(name="search_dataset")
async def search_dataset(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
    dimension: Annotated[str, cyclopts.Parameter(help="")],
    query: Annotated[str, cyclopts.Parameter(help="")],
    edition: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
    version: Annotated[
        str | None,
        cyclopts.Parameter(
            help='JSON Schema: {\n                            "anyOf": [\n                              {\n                                "type": "string"\n                              },\n                              {\n                                "type": "null"\n                              }\n                            ],\n                            "default": null\n                          }'
        ),
    ] = None,
) -> None:
    """Search for values within a dataset dimension.

    Useful for finding specific codes or categories when you know
    the dataset but not the exact dimension value.

    Args:
        id: Dataset ID
        dimension: Dimension name to search (e.g., \'aggregate\')
        query: Search query string
        edition: Edition name (auto-detects if not provided)
        version: Version number (auto-detects if not provided)"""
    # Parse JSON parameters
    edition_parsed = json.loads(edition) if isinstance(edition, str) else edition
    version_parsed = json.loads(version) if isinstance(version, str) else version

    await _call_tool(
        "search_dataset",
        {
            "id": id,
            "dimension": dimension,
            "query": query,
            "edition": edition_parsed,
            "version": version_parsed,
        },
    )


@call_tool_app.command(name="list_codelists")
async def list_codelists() -> None:
    """List all available code lists (standardized categories).

    Code lists provide standardized values for dimensions across datasets,
    such as geography codes, time periods, or classifications."""
    await _call_tool("list_codelists", {})


@call_tool_app.command(name="get_codelist_info")
async def get_codelist_info(
    *,
    code_id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """Get detailed information about a code list.

    Args:
        code_id: Code list ID (e.g., \'quarter\', \'geography\')"""
    await _call_tool("get_codelist_info", {"code_id": code_id})


@call_tool_app.command(name="get_codelist_editions")
async def get_codelist_editions(
    *,
    code_id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """Get available editions for a code list.

    Args:
        code_id: Code list ID"""
    await _call_tool("get_codelist_editions", {"code_id": code_id})


@call_tool_app.command(name="get_codes")
async def get_codes(
    *,
    code_id: Annotated[str, cyclopts.Parameter(help="")],
    edition: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """Get codes for a specific code list edition.

    Returns the standardized values and their meanings.

    Args:
        code_id: Code list ID
        edition: Edition name"""
    await _call_tool("get_codes", {"code_id": code_id, "edition": edition})


@call_tool_app.command(name="get_code_info")
async def get_code_info(
    *,
    code_id: Annotated[str, cyclopts.Parameter(help="")],
    edition: Annotated[str, cyclopts.Parameter(help="")],
    code: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """Get details for a specific code.

    Args:
        code_id: Code list ID
        edition: Edition name
        code: Code value"""
    await _call_tool(
        "get_code_info", {"code_id": code_id, "edition": edition, "code": code}
    )


@call_tool_app.command(name="get_dev_url")
async def get_dev_url() -> None:
    """Get the ONS developer documentation URL."""
    await _call_tool("get_dev_url", {})


@call_tool_app.command(name="get_qmi_url")
async def get_qmi_url(
    *,
    id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    """Get the Quality and Methodology Information (QMI) URL for a dataset.

    Args:
        id: Dataset ID"""
    await _call_tool("get_qmi_url", {"id": id})


if __name__ == "__main__":
    app()
